baseURL = "/"
languageCode = "en-us"
title = "Code writes"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Stephanie K Williams"
  description = "In solitude, where we are least alone."
  github = "StephanieKWilliams"
  linkedin = "https://www.linkedin.com/in/stephanie-williams-333b75278/"
  email = "williamstephaniek@icloud.com"
  url = "https://www.linkedin.com/in/stephanie-williams-333b75278/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "Kenya"
  enableGitalk = true
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]
  enableSearch = true

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "repo"
    owner = "StephanieKWilliams"
    admin = "StephanieKWilliams"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/StephanieKWilliams"
  [[params.links]]
    title = "Link2"
    href = "https://github.com/StephanieKWilliams"
    icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false